# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d89486c675357bb363e8b06c281525d"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "edikted-extension-app"
handle = "edikted-extension-app"

[build]
dev_store_url = "olavka-test-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
